version: '3'
services:
  oca_data_vault:
    image: humancolossus/oca-data-vault
    build: ./
    command: /bin/bash -c "bundle exec rackup -o 0.0.0.0"
    ports:
      - 9292:9292
    volumes:
      - ./storage:/usr/src/app/storage
    networks:
      - odca

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - odca

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/openapi-1.0.0.yml
    volumes:
      - ./openapi-1.0.0.yml:/openapi-1.0.0.yml
      # - ./openapi-1.0.0.yml:/usr/share/nginx/html/openapi-1.0.0.yml
    networks:
      - odca
    ports:
      - 8000:8080

volumes:
  mongodb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $MONGODB_DATA_PATH

networks:
  odca:
    external: true
