version: '3'
services:
  oca_data_vault:
    image: oca-data-vault:latest
    build: ./
    command: /bin/bash -c "bundle exec rackup -o 0.0.0.0"
    ports:
      - 9292:9292
    volumes:
      - ./:/usr/src/app
    networks:
      - odca

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - odca

volumes:
  mongodb_data:

networks:
  odca:
    external: true
