openapi: 3.0.0
info:
  description: ''
  version: 2.0.0
  title: OCA Data Vault
servers:
- url: 'http://data-vault.localhost/api/v2'
tags:
- name: files
paths:
  "/files":
    post:
      tags:
      - files
      summary: Add file
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: File SAI
  "/files/{SAI}":
    get:
      tags:
      - files
      summary: Download file
      parameters:
      - name: SAI
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
                format: binary
